jjrh_bed/urls.py
from django.urls import path
from . views import bed_list_view,unitname_create_view,bed_management_detail_view, \
	bed_update_view,bed_create_view,dashboard,bed_delete_view,view_all,unitname_list_view,\
	unitname_detail_view,unitname_update_view,unitname_delete_view

app_name = 'jjrh_bed'
urlpatterns = [
	#dashboard
	path('dashboard/',dashboard,name='dashboard'),
	path('view_all/',view_all,name='view_all'),
	#unit create view
	path('create/unit/',unitname_create_view,name='unit_create'),
	path('units/', unitname_list_view, name='units'),
	path('units/<int:id>/', unitname_detail_view, name='units_detail'),
	path('units/<int:id>/update/', unitname_update_view, name='units_update'),
	path('units/<int:id>/delete/', unitname_delete_view, name='units_delete'),

	#bed create view
	path('',bed_list_view,name='beds'),
	path('create/bed/',bed_create_view,name='bed_create'),
	path('update/<int:id>/',bed_update_view,name='update'),
	path('delete/<int:id>/',bed_delete_view,name='delete'),
	path('detail/<int:id>/',bed_management_detail_view,name='detail')
]

jjrhospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jjrh_bed.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jjrh_bed/models.py
from django.db import models
from django.urls import reverse



BED_STATUS_CHOICES = (
        ('Occupied','Occupied'),
        ('Free','Free'),
        ('Impeding','Impeding'),
    )


class UnitName(models.Model):
	Date = models.DateField()
	unit_name = models.CharField(max_length=225)
	# unit_code = models.CharField(max_length=45)
	def __str__(self):
		return self.unit_name


class Bed(models.Model):
	unitname = models.ForeignKey(UnitName,on_delete=models.CASCADE,related_name='unitname')
	bed_number = models.CharField(max_length=56)
	status = models.CharField(
			max_length=34,
			choices=BED_STATUS_CHOICES,
			default='Free',
		)

	def __str__(self):
		return f'{self.bed_number} {self.unitname}'

	def get_absolute_url(self):
		return reverse('jjrh_bed:detail', kwargs={'id':self.id})

jjrh_bed/forms.py
from django import forms
from . models import Bed,UnitName

class Unitname_Form(forms.ModelForm):
	class Meta:
		model = UnitName
		fields  = "__all__"
		widgets = {
			'Date': forms.DateInput(attrs = {
					'type':'date',
				})
		}

class Bed_Form(forms.ModelForm):
	class Meta:
		model = Bed
		fields = "__all__"
		

jjrh_bed/views.py
from django.shortcuts import render, get_object_or_404
from . forms import Unitname_Form,Bed_Form
from . models import Bed,UnitName
from django.contrib import messages
from django.db.models import Count,Q

def dashboard(request):
	beds = Bed.objects.all().count()
	unitnames = UnitName.objects.all().count()
	context = {
		'beds':beds,
		'unitnames':unitnames,
	}
	return render(request,'jjrh_bed/dashboard.html',context)
	
	



def view_all(request):
	unitnames = UnitName.objects.annotate(free_beds = Count('id',filter=Q(unitname__status='Free')),
		occupied_beds=Count('id',filter=Q(unitname__status='Occupied')),
		impeding_beds=Count('id',filter=Q(unitname__status='Impeding')), all_beds=Count('id'))
	context = {
		'unitnames':unitnames,
	}
	return render(request,'jjrh_bed/view_all.html',context)

def bed_list_view(request):
	beds = Bed.objects.all()

	# unitnames =	UnitName.objects.annotate(bed_count = Count('bed'))
	# beds = Bed.objects.values('unitname').annotate(num_units = Count('bed_number'))
	# free = Bed.objects.values('unitname').annotate(free_beds = Count('bed_number')).filter(status='Free')
	# occupied = Bed.objects.values('unitname').annotate(occupied_beds = Count('bed_number')).filter(status='Occupied')
	# print(free)
	# print(occupied)

	# beds = Bed.objects.values('unitname').annotate(free_beds=Count('unitname',filter=Q(status="Free")),
	# 	occupied_beds = Count('unitname',filter=Q(status='Occupied')),
	# 	impeding_beds = Count('unitname',filter=Q(status='Impeding')))

	# for bed in beds:
	# 	print(f"{bed['unitname']} | {bed['free_beds']} | {bed['occupied_beds']} | {bed['impeding_beds']} ")

	# unitnames = UnitName.objects.annotate(free_beds = Count('id',filter=Q(unitname__status='Free')),
	# 	occupied_beds=Count('id',filter=Q(unitname__status='Occupied')),
	# 	impeding_beds=Count('id',filter=Q(unitname__status='Impeding')), all_beds=Count('id'))

	# for unitname in unitnames:
		# print(f'{unitname.unit_name} | {unitname.all_beds} | {unitname.free_beds} | {unitname.occupied_beds} | {unitname.impeding_beds}')

	context = {
		'beds':beds,
	}
	return render(request,'jjrh_bed/bed_list_view.html',context)



def bed_management_detail_view(request,id):
	bed = get_object_or_404(Bed,id=id)
	context = {
		'bed':bed,
	}
	return render(request,'jjrh_bed/bed_management_detail_view.html',context)

def bed_update_view(request, id):
	bed = get_object_or_404(Bed, id=id)
	if request.method == 'POST':
		form = Bed_Form(request.POST, instance=bed)
		if form.is_valid():
			form.save()
	else:
		form = Bed_Form(instance=bed)
	context = {
		'form':form,
		'bed':bed,
	}
	return render(request,'jjrh_bed/bed_create_view.html',context)

def bed_delete_view(request, id):
	bed = get_object_or_404(Bed, id=id)
	if request.method == 'POST':
		bed.delete()
	context = {
		'bed':bed,
	}
	return render(request,'jjrh_bed/bed_delete_view_confirm.html',context)


def bed_create_view(request):
	if request.method == 'POST':
		form = Bed_Form(request.POST)
		if form.is_valid():
			form.save()
			form = Bed_Form()
	else:
		form = Bed_Form()
	context = {
		'form':form,
	}
	return render(request,'jjrh_bed/bed_create_view.html',context)


# def bed_management_view(request):
# 	beds = BedMnagement.objects.all()
# 	context={
# 		'beds':beds,
# 	}
# 	return render(request,'jjrh_bed/bed_manage_view.html',context)

def unitname_create_view(request):
	if request.method == 'POST':
		form = Unitname_Form(request.POST)
		if form.is_valid():
			form.save()
			form = Unitname_Form()
	else:
		form  = Unitname_Form()
	context = {
		'form':form,
	}
	return render(request,'jjrh_bed/unitname_create_view.html',context)

def unitname_list_view(request):
	unitnames = UnitName.objects.all()
	context = {
		'unitnames':unitnames,
	}
	return render(request, 'jjrh_bed/unitname_list_view.html',context)

def unitname_detail_view(request,id):
	unitname = get_object_or_404(UnitName,id=id)
	context = {
		'unitname':unitname,
	}
	return render(request, 'jjrh_bed/unitname_detail_view.html',context)

def unitname_update_view(request,id):
	unitname = get_object_or_404(UnitName,id=id)
	if request.method == 'POST':
		form = Unitname_Form(request.POST, instance =unitname)
		if form.is_valid():
			form.save()
			messages.success(request,'You have successfuly created')
		else:
			messages.danger(request,f'{unitname} has been delete successfuly')
	else:
		form = Unitname_Form(instance=unitname)
	context = {
		'form':form,
	}
	return render(request,'jjrh_bed/unitname_create_view.html',context)

def unitname_delete_view(request,id):
	unitname = get_object_or_404(UnitName,id=id)

	if request.method == "POST":
		unitname.delete()
		messages.success(request,f'{unitname} has been delete successfuly')
	context = {
		'unitname':unitname,
	}
	return render(request,'jjrh_bed/unit_delete_view_confirm.html',context)

jjrh_bed/templates/jjrh_bed/bed_create_view.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
  <div class="row">
    
    <div class="col-sm-3">
      
    </div>
    <div class="col-sm-6">
      <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-12 mb-0">
        {{ form|crispy }}
      </div>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Create Bed</button>
  </form>
    </div>
    <div class="col-md-3">
      
    </div>

  </div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/bed_delete_view_confirm.html
{%extends 'base.html'%}
{%block content %}
<div class="row">
	<div class="col-sm-2">
	
	</div>
	<div class="col-sm-8">
		<form method="POST">
		{%csrf_token%}
		Are realy gonna delete this post <b>{{bed}}</b> ?
		<input class="btn btn-info" type="submit" value="yes">
		</form>
	</div>
	<div class="col-sm-2">
		
	</div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/bed_list_view.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
	<div class="table-responsive-lg">
  <table class="table">
   	<thead>
    <tr>
      <th scope="col">Unit name</th>
      <th scope="col">bed number</th>
      <th scope="col">bed status</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>
    {%for bed in beds%}
    <tr>
      <td> {{bed.unitname}}</td>
      <td> {{bed.bed_number}}</td>
      <td> {{bed.status}}</td>
      <td>
      <a href="{% url 'jjrh_bed:detail' bed.id %}">View</a>
      </td>
    </tr>
{%endfor%}
  </tbody>
  </table>
</div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/bed_management_detail_view.html
{%extends 'base.html'%}
{%block content%}
		<h3>JJU SH.Y.R.H TOTAL BED NUMBER</h3>
	<div class="table-responsive-lg">
	<table class="table">
	<thead>
		<tr>
		<th scope="col">Unit Name</th>
		<th scope="col">Bed Number</th>
		<th scope="col">Bed Status</th>
		<th scope="col">Update</th>
		<th scope="col">Delete</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{bed.unitname}}</td>
			<td>{{bed.bed_number}}</td>
			<td>{{bed.status}}</td>
			<td> <a href="{% url 'jjrh_bed:update' bed.id %}">Update</a></td>
			<td><a href="{% url 'jjrh_bed:delete' bed.id %}">delete</a></td>

		
		</tr>
	</tbody>
	</table>
</div>

{%endblock%}

jjrh_bed/templates/jjrh_bed/dashboard.html
{%extends 'dashboard_base.html'%}
{%block content%}
	<div class="container-fluid">
		<div class="row justify-content-center">
                    <div class="col-lg-3 col-sm-4 col-xs-8">
                        <div class="white-box analytics-info">
                            <h4 class="box-title">Total beds: {{beds}}</h4>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">
                                <li style="padding: 6px;">
                                    <i class="fas fa-bed fa-1x"></i>
                                </li>
                                <li class="ml-auto">
                                    <a href="">
                                        <span class="counter text-info"></span>
                                    <a href="{% url 'jjrh_bed:bed_create' %}"><span class="counter text-info">Add Beds</i></span></a>
                                    </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-xs-8">
                        <div class="white-box analytics-info">
                            <h4 class="box-title">View Beds &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">

                                <li style="padding: 6px;">
                                    <div id="sparklinedash2">
                                    	<i class="fas fa-bed fa-1x"></i>
                                    </div>
                                </li>
                                <li class="ml-auto">
                                	<a href="">
                                		<span class="counter text-info"></span>
                                	<a href="{% url 'jjrh_bed:beds' %}"><span class="counter text-info">View Beds</span></a>
                                	</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-xs-8">
                       	 <div class="white-box analytics-success">
                       	 	<h3 class="box-title">Add Units: {{unitnames}}</h3>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">
                               
                                	<li style="padding: 6px;">
                                  <i class="fas fa-align-center fa-1x"></i>
                                </li>
                                <li class="ml-auto">
                                	<span class="counter text-info">
                                		<a href="{%url 'jjrh_bed:unit_create'%}"><span class="counter text-info">Add Units</span></a>
                                	</span>
                                </li>
                            </ul>
                        </div>  
                    </div>
                     <div class="col-lg-3 col-sm-4 col-xs-8">
                         <div class="white-box analytics-success">
                            <h3 class="box-title">View Units: {{unitnames}}</h3>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">
                               
                                    <li style="padding: 6px;">
                                   <i class="fas fa-align-center fa-1x"></i>
                                </li>
                                <li class="ml-auto">
                                    <span class="counter text-info">
                                        <a href="{%url 'jjrh_bed:units'%}"><span class="counter text-info">View Units</span></a>
                                    </span>
                                </li>
                            </ul>
                        </div>  
                    </div>
                </div>
	</div>
 	<div class="row">
        <div class="col-md-12">
           <div class="white-box text-success text-center">
                <h2>Manage Admins</h2>
            </div>
        </div>
     </div>
     <div class="container-fluid">
		<div class="row justify-content-center">
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="white-box analytics-info">
                            <h3 class="box-title">Total Admins</h3>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">
                                <li style="padding: 6px;">
                                    <i class="fas fa-users fa-4x"></i>
                                </li>
                                <li class="ml-auto">
                                <span class="counter text-success">{{users}}</span>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                        <div class="white-box analytics-info">
                            <h4 class="box-title">Users &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{users}}</h4>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">

                                <li style="padding: 6px;">
                                    <div id="sparklinedash2">
                                    	<i class="fas fa-user-plus fa-4x"></i>
                                    </div>
                                </li>
                                <li class="ml-auto">
                                	<a href="">
                                		<span class="counter text-info"></span>
                                		<a href=""><h2><span class="counter text-success">Add Admin</span></h2></a>
                                	</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 col-xs-12">
                       	 <div class="white-box analytics-success">
                       	 	<h3 class="box-title">View Admins</h3>
                            <ul class="list-inline two-part d-flex align-items-center mb-0">
                               
                                	<li style="padding: 6px;">
                                    <i class=" far fa-chart-bar fa-4x"></i>
                                </li>
                                <li class="ml-auto">
                                	<span class="counter text-info">
                                		<a href=""><h2><span class="text-success">View Admins</span></h2></a>
                                	</span>
                                </li>
                            </ul>
                        </div>  
                    </div>
                </div>
	</div>

{%endblock%}

jjrh_bed/templates/jjrh_bed/unit_delete_view_confirm.html
{%extends 'base.html'%}
{%block content %}
<div class="row">
	<div class="col-sm-2">
	
	</div>
	<div class="col-sm-8">
		<form method="POST">
		{%csrf_token%}
		Are realy gonna delete this post <b>{{unitname}}</b> ?
		<input class="btn btn-info" type="submit" value="yes">
		</form>
	</div>
	<div class="col-sm-2">
		
	</div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/unitname_create_view.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
  <div class="row">
    
    <div class="col-sm-3">
      
    </div>
    <div class="col-sm-6">
      <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-12 mb-0">
        {{ form.Date|as_crispy_field }}
      </div>
      <div class="form-group col-md-12 mb-0">
        {{ form.unit_name|as_crispy_field }}
      </div>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Create Unit</button>
  </form>
    </div>
    <div class="col-md-3">
      
    </div>

  </div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/unitname_detail_view.html
{%extends 'base.html'%}
{%block content%}
		<h3>JJU SH.Y.R.H TOTAL WARD NUMBER</h3>
	<div class="table-responsive-lg">
	<table class="table">
	<thead>
		<tr>
		<th scope="col">Unit Name</th>
		<th scope="col">Date</th>
		<th scope="col">Update</th>
		<th scope="col">Delete</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{unitname.unit_name}}</td>
			<td>{{unitname.Date}}</td>
			<td> <a href="{%url 'jjrh_bed:units_update' unitname.id%}">Update</a></td>
			<td> <a href="{%url 'jjrh_bed:units_delete' unitname.id%}">Delete</a></td>
		</tr>
	</tbody>
	</table>
</div>

{%endblock%}

jjrh_bed/templates/jjrh_bed/unitname_list_view.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
	<div class="table-responsive-lg">
  <table class="table">
   	<thead>
    <tr>
      <th scope="col">Unit name</th>
      <th scope="col">Date</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>
    {%for unitname in unitnames%}
    <tr>
      <td> {{unitname.unit_name}}</td>
      <td> {{unitname.Date}}</td>
      <td>
      <a href="{% url 'jjrh_bed:units_detail' unitname.id %}">View</a>
      </td>
    </tr>
{%endfor%}
  </tbody>
  </table>
</div>
</div>
{%endblock%}

jjrh_bed/templates/jjrh_bed/view_all.html
{%extends 'dashboard_base.html'%}
{%block content%}
<div class="table-responsive-lg">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Unit Names</th>
      <th scope="col">All Beds</th>
      <th scope="col">Free Beds</th>
      <th scope="col">Occupied Beds</th>
      <th scope="col">Impeding Beds</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>
    {%for unitname in unitnames%}
    <tr>
      <td> {{unitname.unit_name}}</td>
  <td>{{unitname.all_beds}}</td>
  <td>{{unitname.free_beds}}</td>
  <td>{{unitname.occupied_beds}}</td>
  <td>{{unitname.impeding_beds}}</td>  
      <td>
      <a href="">download</a>
      </td>

    </tr>
{%endfor%}
  </tbody>
  </table>
</div>
{%endblock%}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Jigjiga Refral Hospital</title>
  </head>
  <body>
    {% include 'includes/navbar.html'%}
    <div class="container-fluid mt-5 mb-5">
      {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
      {%block content%}

    {%endblock%}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/includes/navbar.html
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{%url 'jjrh_bed:dashboard' %}" class="navbar-brand">JJRH Dashboard</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a href="{% url 'jjrh_bed:beds'%}" class="nav-link">Home</a>
            </li>
           <!--  <li class="nav-item">
                <a href="#" class="nav-link">Profile</a>
            </li> -->
            <!-- <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Messages</a>
                <div class="dropdown-menu">
                    <a href="#" class="dropdown-item">Inbox</a>
                    <a href="#" class="dropdown-item">Drafts</a>
                    <a href="#" class="dropdown-item">Sent Items</a>
                    <div class="dropdown-divider"></div>
                    <a href="#"class="dropdown-item">Trash</a>
                </div>
            </li> -->
        </ul>
        <ul class="nav navbar-nav ml-auto">

        <a href="#" class="nav-link">Hello</a>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Account</a>
                <div class="dropdown-menu dropdown-menu-right">
                    {%if request.user.is_authenticated%}
                    <!-- <div class="dropdown-divider"></div> -->
                    <a href=""class="dropdown-item">Profile</a>
                    <a href=""class="dropdown-item">Change Password</a>
                    <a href=""class="dropdown-item">Logout</a>
                    {%else%}
                    <a href="" class="dropdown-item">login</a>
                    <a href="" class="dropdown-item">register</a>
                    {%endif%}
                </div>
            </li>
        </ul>
    </div>
</nav>